# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tmsvison.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1515, 964)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 800))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("/*\n"
"Aqua Style Sheet for QT Applications\n"
"Author: Jaime A. Quiroga P.\n"
"Company: GTRONICK\n"
"Last updated: 22/01/2019, 07:55.\n"
"Available at: https://github.com/GTRONICK/QSS/blob/master/Aqua.qss\n"
"*/\n"
"QMainWindow {\n"
"    background-color:#ececec;\n"
"}\n"
"\n"
"*{font: normal 20px \"微软雅黑\";}\n"
"\n"
"QComboBox {\n"
"    border: 2px solid rgb(51,51,51);\n"
"    border-radius: 5px;    \n"
"    color:rgb(0,0,0);\n"
"    background-color: rgb(207,207,207);\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid rgb(0,143,170);\n"
"    border-radius: 5px;    \n"
"    color:rgb(0,0,0);\n"
"    background-color: rgb(0,143,170);\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"    background: rgb(207,207,207);\n"
"}\n"
"\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background:rgb(207,207,207);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 5px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(icons/1x/arrow.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    background:rgb(207,207,207);\n"
"}\n"
"\n"
"QTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QPlainTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QToolButton {\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QToolButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(197, 197, 197), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(197, 197, 197));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QToolButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(207,207,207);;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(197, 197, 197), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(197, 197, 197));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgba(34, 142, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-style: solid;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QLabel {\n"
"    color: #000000;\n"
"}\n"
"QLCDNumber {\n"
"    color: rgb(0, 113, 255, 255);\n"
"}\n"
"/*\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(230, 230, 230);\n"
"    border-style: solid;\n"
"    background-color:rgb(207,207,207);\n"
"}\n"
"*/\n"
"/*\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(49, 147, 250, 255), stop:1 rgba(34, 142, 255, 255));\n"
"    border-radius: 10px;\n"
"}\n"
"*/\n"
"QMenuBar {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(207, 209, 207, 255), stop:1 rgba(230, 229, 230, 255));\n"
"}\n"
"QMenuBar::item {\n"
"    color: #000000;\n"
"      spacing: 3px;\n"
"      padding: 1px 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(207, 209, 207, 255), stop:1 rgba(230, 229, 230, 255));\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu::item:selected {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    border-bottom-color: transparent;\n"
"    border-left-width: 2px;\n"
"    color: #000000;\n"
"    padding-left:15px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"}\n"
"QMenu::item {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    color: #000000;\n"
"    padding-left:17px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#000000;\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(223,223,223);\n"
"        background-color:rgb(226,226,226);\n"
"        border-style: solid;\n"
"        border-width: 2px;\n"
"        border-radius: 6px;\n"
"}\n"
"QTabBar::tab:first {\n"
"    border-style: solid;\n"
"    border-left-width:1px;\n"
"    border-right-width:0px;\n"
"    border-top-width:1px;\n"
"    border-bottom-width:1px;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    color: #000000;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(247, 247, 247, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QTabBar::tab:last {\n"
"    border-style: solid;\n"
"    border-width:1px;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    color: #000000;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(247, 247, 247, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QTabBar::tab {\n"
"    border-style: solid;\n"
"    border-top-width:1px;\n"
"    border-bottom-width:1px;\n"
"    border-left-width:1px;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    color: #000000;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(247, 247, 247, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"      border-left-width:1px;\n"
"    border-right-color: transparent;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    color: #FFFFFF;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:first:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"      border-left-width:1px;\n"
"      border-bottom-width:1px;\n"
"      border-top-width:1px;\n"
"    border-right-color: transparent;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(209, 209, 209, 209), stop:1 rgba(229, 229, 229, 229));\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    color: #FFFFFF;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #000000;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: transparent;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    color: #000000;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    color: #000000;\n"
"}\n"
"QRadioButton {\n"
"    color: 000000;\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    color: #a9b7c6;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QStatusBar {\n"
"    color:#027f7f;\n"
"}\n"
"QSpinBox {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QDoubleSpinBox {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QTimeEdit {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QDateTimeEdit {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"QDateEdit {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"}\n"
"\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color:#000000;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color:#000000;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color:#000000;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color:#000000;\n"
"}\n"
"/*\n"
"QSlider::groove{\n"
"    height: 25px; \n"
"    background:  rgb(207,207,207);\n"
"    border-radius: 3px; \n"
"}\n"
"\n"
"\n"
"\n"
"QSlider::handle{\n"
"    background: rgba(34, 142, 255, 255);\n"
"    width: 45px;\n"
"    border-radius: 3px; \n"
"}\n"
"*/\n"
"\n"
"/* 已划过的设置*/\n"
"/*\n"
"QSlider::sub-page:horizontal{\n"
"    background: rgb(207,207,207);\n"
"    border-radius: 3px;\n"
"    height: 25px; \n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    max-height: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 0px 20px 0px 20px;\n"
"}\n"
"QScrollBar:vertical {\n"
"    max-width: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(147, 200, 200);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(147, 200, 200);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"   border: 2px transparent grey;\n"
"   border-top-right-radius: 7px;\n"
"   border-bottom-right-radius: 7px;\n"
"   background: rgba(34, 142, 255, 255);\n"
"   width: 20px;\n"
"   subcontrol-position: right;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-right-radius: 7px;\n"
"   border-bottom-right-radius: 7px;\n"
"   background: rgb(181,181,181);\n"
"   width: 20px;\n"
"   subcontrol-position: right;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"   border: 2px transparent grey;\n"
"   border-bottom-left-radius: 7px;\n"
"   border-bottom-right-radius: 7px;\n"
"   background: rgba(34, 142, 255, 255);\n"
"   height: 20px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-bottom-left-radius: 7px;\n"
"   border-bottom-right-radius: 7px;\n"
"   background: rgb(181,181,181);\n"
"   height: 20px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 7px;\n"
"   border-bottom-left-radius: 7px;\n"
"   background: rgba(34, 142, 255, 255);\n"
"   width: 20px;\n"
"   subcontrol-position: left;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 7px;\n"
"   border-bottom-left-radius: 7px;\n"
"   background: rgb(181,181,181);\n"
"   width: 20px;\n"
"   subcontrol-position: left;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 7px;\n"
"   border-top-right-radius: 7px;\n"
"   background: rgba(34, 142, 255, 255);\n"
"   height: 20px;\n"
"   subcontrol-position: top;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 7px;\n"
"   border-top-right-radius: 7px;\n"
"   background: rgb(181,181,181);\n"
"   height: 20px;\n"
"   subcontrol-position: top;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"   border: 1px transparent grey;\n"
"   border-top-left-radius: 3px;\n"
"   border-bottom-left-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"   border: 1px transparent grey;\n"
"   border-top-right-radius: 3px;\n"
"   border-bottom-right-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"   border: 1px transparent grey;\n"
"   border-top-left-radius: 3px;\n"
"   border-top-right-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"   border: 1px transparent grey;\n"
"   border-bottom-left-radius: 3px;\n"
"   border-bottom-right-radius: 3px;\n"
"   width: 6px;\n"
"   height: 6px;\n"
"   background: white;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"   background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"   background: none;\n"
"}\n"
"*/")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(780, 10, 711, 601))
        self.groupBox.setObjectName("groupBox")
        self.dicomButton = QtWidgets.QPushButton(self.groupBox)
        self.dicomButton.setGeometry(QtCore.QRect(510, 0, 206, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dicomButton.sizePolicy().hasHeightForWidth())
        self.dicomButton.setSizePolicy(sizePolicy)
        self.dicomButton.setMinimumSize(QtCore.QSize(206, 0))
        self.dicomButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.dicomButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dicomButton.setStyleSheet("")
        self.dicomButton.setObjectName("dicomButton")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 40, 351, 281))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.axialGrid = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.axialGrid.setContentsMargins(0, 0, 0, 0)
        self.axialGrid.setObjectName("axialGrid")
        self.axial_vBox = QtWidgets.QVBoxLayout()
        self.axial_vBox.setSpacing(6)
        self.axial_vBox.setObjectName("axial_vBox")
        self.axial_hBox = QtWidgets.QHBoxLayout()
        self.axial_hBox.setObjectName("axial_hBox")
        self.imgLabel_1 = QPaintLabel3(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgLabel_1.sizePolicy().hasHeightForWidth())
        self.imgLabel_1.setSizePolicy(sizePolicy)
        self.imgLabel_1.setMinimumSize(QtCore.QSize(1, 1))
        self.imgLabel_1.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.imgLabel_1.setFrameShape(QtWidgets.QFrame.Panel)
        self.imgLabel_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.imgLabel_1.setText("")
        self.imgLabel_1.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLabel_1.setObjectName("imgLabel_1")
        self.axial_hBox.addWidget(self.imgLabel_1)
        self.axial_vBox.addLayout(self.axial_hBox)
        self.axialGrid.addLayout(self.axial_vBox, 1, 1, 1, 1)
        self.axial_vSlider = QtWidgets.QSlider(self.layoutWidget_2)
        self.axial_vSlider.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axial_vSlider.sizePolicy().hasHeightForWidth())
        self.axial_vSlider.setSizePolicy(sizePolicy)
        self.axial_vSlider.setMinimumSize(QtCore.QSize(0, 1))
        self.axial_vSlider.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.axial_vSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.axial_vSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.axial_vSlider.setMaximum(255)
        self.axial_vSlider.setPageStep(9)
        self.axial_vSlider.setProperty("value", 128)
        self.axial_vSlider.setSliderPosition(128)
        self.axial_vSlider.setTracking(True)
        self.axial_vSlider.setOrientation(QtCore.Qt.Vertical)
        self.axial_vSlider.setInvertedAppearance(True)
        self.axial_vSlider.setInvertedControls(False)
        self.axial_vSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.axial_vSlider.setTickInterval(1)
        self.axial_vSlider.setObjectName("axial_vSlider")
        self.axialGrid.addWidget(self.axial_vSlider, 1, 0, 1, 1)
        self.axial_hSlider = QtWidgets.QSlider(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axial_hSlider.sizePolicy().hasHeightForWidth())
        self.axial_hSlider.setSizePolicy(sizePolicy)
        self.axial_hSlider.setMinimumSize(QtCore.QSize(1, 0))
        self.axial_hSlider.setCursor(QtGui.QCursor(QtCore.Qt.SplitHCursor))
        self.axial_hSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.axial_hSlider.setStyleSheet("")
        self.axial_hSlider.setMaximum(255)
        self.axial_hSlider.setProperty("value", 128)
        self.axial_hSlider.setTracking(True)
        self.axial_hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.axial_hSlider.setInvertedAppearance(False)
        self.axial_hSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.axial_hSlider.setTickInterval(1)
        self.axial_hSlider.setObjectName("axial_hSlider")
        self.axialGrid.addWidget(self.axial_hSlider, 0, 1, 1, 1)
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(350, 40, 331, 281))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.saggitalGrid = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.saggitalGrid.setContentsMargins(0, 0, 0, 0)
        self.saggitalGrid.setObjectName("saggitalGrid")
        self.saggital_vBox = QtWidgets.QVBoxLayout()
        self.saggital_vBox.setObjectName("saggital_vBox")
        self.saggital_hBox = QtWidgets.QHBoxLayout()
        self.saggital_hBox.setObjectName("saggital_hBox")
        self.imgLabel_2 = QPaintLabel3(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgLabel_2.sizePolicy().hasHeightForWidth())
        self.imgLabel_2.setSizePolicy(sizePolicy)
        self.imgLabel_2.setMinimumSize(QtCore.QSize(1, 1))
        self.imgLabel_2.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.imgLabel_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.imgLabel_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.imgLabel_2.setText("")
        self.imgLabel_2.setObjectName("imgLabel_2")
        self.saggital_hBox.addWidget(self.imgLabel_2)
        self.saggital_vBox.addLayout(self.saggital_hBox)
        self.saggitalGrid.addLayout(self.saggital_vBox, 1, 1, 1, 1)
        self.sagittal_hSlider = QtWidgets.QSlider(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sagittal_hSlider.sizePolicy().hasHeightForWidth())
        self.sagittal_hSlider.setSizePolicy(sizePolicy)
        self.sagittal_hSlider.setMinimumSize(QtCore.QSize(1, 0))
        self.sagittal_hSlider.setCursor(QtGui.QCursor(QtCore.Qt.SplitHCursor))
        self.sagittal_hSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sagittal_hSlider.setStyleSheet("")
        self.sagittal_hSlider.setMaximum(255)
        self.sagittal_hSlider.setProperty("value", 128)
        self.sagittal_hSlider.setTracking(True)
        self.sagittal_hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sagittal_hSlider.setInvertedAppearance(False)
        self.sagittal_hSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sagittal_hSlider.setTickInterval(1)
        self.sagittal_hSlider.setObjectName("sagittal_hSlider")
        self.saggitalGrid.addWidget(self.sagittal_hSlider, 0, 1, 1, 1)
        self.sagittal_vSlider = QtWidgets.QSlider(self.layoutWidget_3)
        self.sagittal_vSlider.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sagittal_vSlider.sizePolicy().hasHeightForWidth())
        self.sagittal_vSlider.setSizePolicy(sizePolicy)
        self.sagittal_vSlider.setMinimumSize(QtCore.QSize(0, 1))
        self.sagittal_vSlider.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.sagittal_vSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sagittal_vSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sagittal_vSlider.setMaximum(255)
        self.sagittal_vSlider.setPageStep(9)
        self.sagittal_vSlider.setProperty("value", 128)
        self.sagittal_vSlider.setSliderPosition(128)
        self.sagittal_vSlider.setTracking(True)
        self.sagittal_vSlider.setOrientation(QtCore.Qt.Vertical)
        self.sagittal_vSlider.setInvertedAppearance(True)
        self.sagittal_vSlider.setInvertedControls(False)
        self.sagittal_vSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sagittal_vSlider.setTickInterval(1)
        self.sagittal_vSlider.setObjectName("sagittal_vSlider")
        self.saggitalGrid.addWidget(self.sagittal_vSlider, 1, 0, 1, 1)
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_4.setGeometry(QtCore.QRect(350, 320, 331, 271))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.coronalGrid = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.coronalGrid.setContentsMargins(0, 0, 0, 0)
        self.coronalGrid.setObjectName("coronalGrid")
        self.coronal_vSlider = QtWidgets.QSlider(self.layoutWidget_4)
        self.coronal_vSlider.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coronal_vSlider.sizePolicy().hasHeightForWidth())
        self.coronal_vSlider.setSizePolicy(sizePolicy)
        self.coronal_vSlider.setMinimumSize(QtCore.QSize(0, 1))
        self.coronal_vSlider.setCursor(QtGui.QCursor(QtCore.Qt.SplitVCursor))
        self.coronal_vSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.coronal_vSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.coronal_vSlider.setMaximum(255)
        self.coronal_vSlider.setPageStep(9)
        self.coronal_vSlider.setProperty("value", 128)
        self.coronal_vSlider.setSliderPosition(128)
        self.coronal_vSlider.setTracking(True)
        self.coronal_vSlider.setOrientation(QtCore.Qt.Vertical)
        self.coronal_vSlider.setInvertedAppearance(True)
        self.coronal_vSlider.setInvertedControls(False)
        self.coronal_vSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.coronal_vSlider.setTickInterval(1)
        self.coronal_vSlider.setObjectName("coronal_vSlider")
        self.coronalGrid.addWidget(self.coronal_vSlider, 1, 0, 1, 1)
        self.coronal_hSlider = QtWidgets.QSlider(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coronal_hSlider.sizePolicy().hasHeightForWidth())
        self.coronal_hSlider.setSizePolicy(sizePolicy)
        self.coronal_hSlider.setMinimumSize(QtCore.QSize(1, 0))
        self.coronal_hSlider.setCursor(QtGui.QCursor(QtCore.Qt.SplitHCursor))
        self.coronal_hSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.coronal_hSlider.setStyleSheet("")
        self.coronal_hSlider.setMaximum(255)
        self.coronal_hSlider.setProperty("value", 128)
        self.coronal_hSlider.setTracking(True)
        self.coronal_hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.coronal_hSlider.setInvertedAppearance(False)
        self.coronal_hSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.coronal_hSlider.setTickInterval(1)
        self.coronal_hSlider.setObjectName("coronal_hSlider")
        self.coronalGrid.addWidget(self.coronal_hSlider, 0, 1, 1, 1)
        self.coronal_vBox = QtWidgets.QVBoxLayout()
        self.coronal_vBox.setObjectName("coronal_vBox")
        self.coronal_hBox = QtWidgets.QHBoxLayout()
        self.coronal_hBox.setObjectName("coronal_hBox")
        self.imgLabel_3 = QPaintLabel3(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgLabel_3.sizePolicy().hasHeightForWidth())
        self.imgLabel_3.setSizePolicy(sizePolicy)
        self.imgLabel_3.setMinimumSize(QtCore.QSize(1, 1))
        self.imgLabel_3.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.imgLabel_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.imgLabel_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.imgLabel_3.setText("")
        self.imgLabel_3.setObjectName("imgLabel_3")
        self.coronal_hBox.addWidget(self.imgLabel_3)
        self.coronal_vBox.addLayout(self.coronal_hBox)
        self.coronalGrid.addLayout(self.coronal_vBox, 1, 1, 1, 1)
        self.colormapBox = QtWidgets.QComboBox(self.groupBox)
        self.colormapBox.setGeometry(QtCore.QRect(390, 0, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colormapBox.sizePolicy().hasHeightForWidth())
        self.colormapBox.setSizePolicy(sizePolicy)
        self.colormapBox.setMinimumSize(QtCore.QSize(1, 0))
        self.colormapBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.colormapBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.colormapBox.setObjectName("colormapBox")
        self.colormapBox.addItem("")
        self.colormapBox.addItem("")
        self.colormapBox.addItem("")
        self.colormapBox.addItem("")
        self.colormapBox.addItem("")
        self.colormapBox.addItem("")
        self.colormapBox.addItem("")
        self.colormapBox.addItem("")
        self.colormapBox.addItem("")
        self.colormapBox.addItem("")
        self.colormapBox.addItem("")
        self.colormapBox.addItem("")
        self.colormapBox.addItem("")
        self.dcmList = QtWidgets.QListWidget(self.groupBox)
        self.dcmList.setGeometry(QtCore.QRect(10, 370, 331, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dcmList.sizePolicy().hasHeightForWidth())
        self.dcmList.setSizePolicy(sizePolicy)
        self.dcmList.setMinimumSize(QtCore.QSize(320, 180))
        self.dcmList.setMaximumSize(QtCore.QSize(800, 100))
        self.dcmList.setObjectName("dcmList")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 340, 151, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(1, 0))
        self.label_5.setObjectName("label_5")
        self.privatecheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.privatecheckBox.setGeometry(QtCore.QRect(130, 560, 221, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.privatecheckBox.sizePolicy().hasHeightForWidth())
        self.privatecheckBox.setSizePolicy(sizePolicy)
        self.privatecheckBox.setObjectName("privatecheckBox")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 20, 601, 881))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbvideo = QtWidgets.QLabel(self.layoutWidget)
        self.lbvideo.setObjectName("lbvideo")
        self.verticalLayout.addWidget(self.lbvideo)
        self.lbmodel = QtWidgets.QLabel(self.layoutWidget)
        self.lbmodel.setObjectName("lbmodel")
        self.verticalLayout.addWidget(self.lbmodel)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(19, 20, 131, 841))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(10, 30, 10, 30)
        self.verticalLayout_3.setSpacing(150)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pb1 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb1.sizePolicy().hasHeightForWidth())
        self.pb1.setSizePolicy(sizePolicy)
        self.pb1.setMinimumSize(QtCore.QSize(0, 1))
        self.pb1.setIconSize(QtCore.QSize(16, 16))
        self.pb1.setObjectName("pb1")
        self.verticalLayout_3.addWidget(self.pb1)
        self.pb2 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb2.sizePolicy().hasHeightForWidth())
        self.pb2.setSizePolicy(sizePolicy)
        self.pb2.setObjectName("pb2")
        self.verticalLayout_3.addWidget(self.pb2)
        self.pb3 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb3.sizePolicy().hasHeightForWidth())
        self.pb3.setSizePolicy(sizePolicy)
        self.pb3.setObjectName("pb3")
        self.verticalLayout_3.addWidget(self.pb3)
        self.pb4 = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb4.sizePolicy().hasHeightForWidth())
        self.pb4.setSizePolicy(sizePolicy)
        self.pb4.setObjectName("pb4")
        self.verticalLayout_3.addWidget(self.pb4)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(780, 620, 711, 281))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pos_y = QtWidgets.QLineEdit(self.tab)
        self.pos_y.setGeometry(QtCore.QRect(279, 140, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_y.sizePolicy().hasHeightForWidth())
        self.pos_y.setSizePolicy(sizePolicy)
        self.pos_y.setObjectName("pos_y")
        self.pos_z = QtWidgets.QLineEdit(self.tab)
        self.pos_z.setGeometry(QtCore.QRect(399, 140, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_z.sizePolicy().hasHeightForWidth())
        self.pos_z.setSizePolicy(sizePolicy)
        self.pos_z.setObjectName("pos_z")
        self.nor_z = QtWidgets.QLineEdit(self.tab)
        self.nor_z.setGeometry(QtCore.QRect(399, 180, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nor_z.sizePolicy().hasHeightForWidth())
        self.nor_z.setSizePolicy(sizePolicy)
        self.nor_z.setObjectName("nor_z")
        self.nor_y = QtWidgets.QLineEdit(self.tab)
        self.nor_y.setGeometry(QtCore.QRect(279, 180, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nor_y.sizePolicy().hasHeightForWidth())
        self.nor_y.setSizePolicy(sizePolicy)
        self.nor_y.setObjectName("nor_y")
        self.nor_x = QtWidgets.QLineEdit(self.tab)
        self.nor_x.setGeometry(QtCore.QRect(159, 180, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nor_x.sizePolicy().hasHeightForWidth())
        self.nor_x.setSizePolicy(sizePolicy)
        self.nor_x.setObjectName("nor_x")
        self.pb_readdata = QtWidgets.QPushButton(self.tab)
        self.pb_readdata.setGeometry(QtCore.QRect(370, 220, 121, 31))
        self.pb_readdata.setObjectName("pb_readdata")
        self.lb32 = QtWidgets.QLabel(self.tab)
        self.lb32.setGeometry(QtCore.QRect(160, 90, 291, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb32.sizePolicy().hasHeightForWidth())
        self.lb32.setSizePolicy(sizePolicy)
        self.lb32.setAlignment(QtCore.Qt.AlignCenter)
        self.lb32.setObjectName("lb32")
        self.lb21 = QtWidgets.QLabel(self.tab)
        self.lb21.setGeometry(QtCore.QRect(20, 50, 114, 27))
        self.lb21.setAlignment(QtCore.Qt.AlignCenter)
        self.lb21.setObjectName("lb21")
        self.lb22 = QtWidgets.QLabel(self.tab)
        self.lb22.setGeometry(QtCore.QRect(160, 50, 291, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb22.sizePolicy().hasHeightForWidth())
        self.lb22.setSizePolicy(sizePolicy)
        self.lb22.setAlignment(QtCore.Qt.AlignCenter)
        self.lb22.setObjectName("lb22")
        self.lb31 = QtWidgets.QLabel(self.tab)
        self.lb31.setGeometry(QtCore.QRect(20, 90, 98, 27))
        self.lb31.setAlignment(QtCore.Qt.AlignCenter)
        self.lb31.setObjectName("lb31")
        self.lb12 = QtWidgets.QLabel(self.tab)
        self.lb12.setGeometry(QtCore.QRect(150, 10, 291, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb12.sizePolicy().hasHeightForWidth())
        self.lb12.setSizePolicy(sizePolicy)
        self.lb12.setAlignment(QtCore.Qt.AlignCenter)
        self.lb12.setObjectName("lb12")
        self.lb11 = QtWidgets.QLabel(self.tab)
        self.lb11.setGeometry(QtCore.QRect(20, 10, 101, 27))
        self.lb11.setAlignment(QtCore.Qt.AlignCenter)
        self.lb11.setObjectName("lb11")
        self.lb31_3 = QtWidgets.QLabel(self.tab)
        self.lb31_3.setGeometry(QtCore.QRect(20, 140, 100, 27))
        self.lb31_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb31_3.setObjectName("lb31_3")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 100, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pos_x = QtWidgets.QLineEdit(self.tab)
        self.pos_x.setGeometry(QtCore.QRect(159, 140, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_x.sizePolicy().hasHeightForWidth())
        self.pos_x.setSizePolicy(sizePolicy)
        self.pos_x.setObjectName("pos_x")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(21, 220, 100, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.tms2head = QtWidgets.QLineEdit(self.tab)
        self.tms2head.setGeometry(QtCore.QRect(160, 220, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tms2head.sizePolicy().hasHeightForWidth())
        self.tms2head.setSizePolicy(sizePolicy)
        self.tms2head.setObjectName("tms2head")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(270, 220, 61, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 121, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 90, 121, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 170, 121, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 250, 121, 61))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 320, 121, 61))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(-40, -10, 567, 391))
        self.tabWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_2.setAutoFillBackground(False)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 0, 456, 362))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lb32_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.lb32_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb32_2.setObjectName("lb32_2")
        self.gridLayout_3.addWidget(self.lb32_2, 4, 1, 1, 1)
        self.lb42_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.lb42_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb42_2.setObjectName("lb42_2")
        self.gridLayout_3.addWidget(self.lb42_2, 5, 1, 1, 1)
        self.lb21_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.lb21_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb21_2.setObjectName("lb21_2")
        self.gridLayout_3.addWidget(self.lb21_2, 3, 0, 1, 1)
        self.lb22_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.lb22_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb22_2.setObjectName("lb22_2")
        self.gridLayout_3.addWidget(self.lb22_2, 3, 1, 1, 1)
        self.lb31_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.lb31_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb31_2.setObjectName("lb31_2")
        self.gridLayout_3.addWidget(self.lb31_2, 4, 0, 1, 1)
        self.lb12_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.lb12_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb12_2.setObjectName("lb12_2")
        self.gridLayout_3.addWidget(self.lb12_2, 2, 1, 1, 1)
        self.lb41_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.lb41_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb41_2.setObjectName("lb41_2")
        self.gridLayout_3.addWidget(self.lb41_2, 5, 0, 1, 1)
        self.lb11_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.lb11_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb11_2.setObjectName("lb11_2")
        self.gridLayout_3.addWidget(self.lb11_2, 2, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.line = QtWidgets.QFrame(self.tab_4)
        self.line.setGeometry(QtCore.QRect(330, 50, 20, 201))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget_5.setGeometry(QtCore.QRect(360, 50, 158, 230))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pb_txd = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pb_txd.setObjectName("pb_txd")
        self.gridLayout_8.addWidget(self.pb_txd, 0, 0, 1, 1)
        self.pb_txa = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pb_txa.setObjectName("pb_txa")
        self.gridLayout_8.addWidget(self.pb_txa, 0, 1, 1, 1)
        self.pb_tyd = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pb_tyd.setObjectName("pb_tyd")
        self.gridLayout_8.addWidget(self.pb_tyd, 1, 0, 1, 1)
        self.pb_tya = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pb_tya.setObjectName("pb_tya")
        self.gridLayout_8.addWidget(self.pb_tya, 1, 1, 1, 1)
        self.pb_tzd = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pb_tzd.setObjectName("pb_tzd")
        self.gridLayout_8.addWidget(self.pb_tzd, 2, 0, 1, 1)
        self.pb_tza = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pb_tza.setObjectName("pb_tza")
        self.gridLayout_8.addWidget(self.pb_tza, 2, 1, 1, 1)
        self.pb_tad = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pb_tad.setObjectName("pb_tad")
        self.gridLayout_8.addWidget(self.pb_tad, 3, 0, 1, 1)
        self.pb_taa = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pb_taa.setObjectName("pb_taa")
        self.gridLayout_8.addWidget(self.pb_taa, 3, 1, 1, 1)
        self.pb_tbd = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pb_tbd.setObjectName("pb_tbd")
        self.gridLayout_8.addWidget(self.pb_tbd, 4, 0, 1, 1)
        self.pb_tba = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pb_tba.setObjectName("pb_tba")
        self.gridLayout_8.addWidget(self.pb_tba, 4, 1, 1, 1)
        self.pb_tcd = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pb_tcd.setObjectName("pb_tcd")
        self.gridLayout_8.addWidget(self.pb_tcd, 5, 0, 1, 1)
        self.pb_tca = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pb_tca.setObjectName("pb_tca")
        self.gridLayout_8.addWidget(self.pb_tca, 5, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab_4)
        self.line_3.setGeometry(QtCore.QRect(130, 10, 21, 241))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(160, 50, 161, 230))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pb_j1d = QtWidgets.QPushButton(self.layoutWidget3)
        self.pb_j1d.setObjectName("pb_j1d")
        self.gridLayout_7.addWidget(self.pb_j1d, 0, 0, 1, 1)
        self.pb_j1a = QtWidgets.QPushButton(self.layoutWidget3)
        self.pb_j1a.setObjectName("pb_j1a")
        self.gridLayout_7.addWidget(self.pb_j1a, 0, 1, 1, 1)
        self.pb_j2d = QtWidgets.QPushButton(self.layoutWidget3)
        self.pb_j2d.setObjectName("pb_j2d")
        self.gridLayout_7.addWidget(self.pb_j2d, 1, 0, 1, 1)
        self.pb_j2a = QtWidgets.QPushButton(self.layoutWidget3)
        self.pb_j2a.setObjectName("pb_j2a")
        self.gridLayout_7.addWidget(self.pb_j2a, 1, 1, 1, 1)
        self.pb_j3d = QtWidgets.QPushButton(self.layoutWidget3)
        self.pb_j3d.setObjectName("pb_j3d")
        self.gridLayout_7.addWidget(self.pb_j3d, 2, 0, 1, 1)
        self.pb_j3a = QtWidgets.QPushButton(self.layoutWidget3)
        self.pb_j3a.setObjectName("pb_j3a")
        self.gridLayout_7.addWidget(self.pb_j3a, 2, 1, 1, 1)
        self.pb_j4d = QtWidgets.QPushButton(self.layoutWidget3)
        self.pb_j4d.setObjectName("pb_j4d")
        self.gridLayout_7.addWidget(self.pb_j4d, 3, 0, 1, 1)
        self.pb_j4a = QtWidgets.QPushButton(self.layoutWidget3)
        self.pb_j4a.setObjectName("pb_j4a")
        self.gridLayout_7.addWidget(self.pb_j4a, 3, 1, 1, 1)
        self.pb_j5d = QtWidgets.QPushButton(self.layoutWidget3)
        self.pb_j5d.setObjectName("pb_j5d")
        self.gridLayout_7.addWidget(self.pb_j5d, 4, 0, 1, 1)
        self.pb_j5a = QtWidgets.QPushButton(self.layoutWidget3)
        self.pb_j5a.setObjectName("pb_j5a")
        self.gridLayout_7.addWidget(self.pb_j5a, 4, 1, 1, 1)
        self.pb_j6d = QtWidgets.QPushButton(self.layoutWidget3)
        self.pb_j6d.setObjectName("pb_j6d")
        self.gridLayout_7.addWidget(self.pb_j6d, 5, 0, 1, 1)
        self.pb_j6a = QtWidgets.QPushButton(self.layoutWidget3)
        self.pb_j6a.setObjectName("pb_j6a")
        self.gridLayout_7.addWidget(self.pb_j6a, 5, 1, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget4.setGeometry(QtCore.QRect(160, 10, 351, 41))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget4)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pb_setspeed = QtWidgets.QPushButton(self.layoutWidget4)
        self.pb_setspeed.setObjectName("pb_setspeed")
        self.horizontalLayout_2.addWidget(self.pb_setspeed)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 2)
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 10, 111, 258))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pb_zt = QtWidgets.QPushButton(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_zt.sizePolicy().hasHeightForWidth())
        self.pb_zt.setSizePolicy(sizePolicy)
        self.pb_zt.setObjectName("pb_zt")
        self.verticalLayout_2.addWidget(self.pb_zt)
        self.pb_tc = QtWidgets.QPushButton(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_tc.sizePolicy().hasHeightForWidth())
        self.pb_tc.setSizePolicy(sizePolicy)
        self.pb_tc.setObjectName("pb_tc")
        self.verticalLayout_2.addWidget(self.pb_tc)
        self.pb_sj = QtWidgets.QPushButton(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_sj.sizePolicy().hasHeightForWidth())
        self.pb_sj.setSizePolicy(sizePolicy)
        self.pb_sj.setObjectName("pb_sj")
        self.verticalLayout_2.addWidget(self.pb_sj)
        self.pb_fw = QtWidgets.QPushButton(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_fw.sizePolicy().hasHeightForWidth())
        self.pb_fw.setSizePolicy(sizePolicy)
        self.pb_fw.setObjectName("pb_fw")
        self.verticalLayout_2.addWidget(self.pb_fw)
        self.pb_yx = QtWidgets.QPushButton(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_yx.sizePolicy().hasHeightForWidth())
        self.pb_yx.setSizePolicy(sizePolicy)
        self.pb_yx.setObjectName("pb_yx")
        self.verticalLayout_2.addWidget(self.pb_yx)
        self.pb_cq = QtWidgets.QPushButton(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_cq.sizePolicy().hasHeightForWidth())
        self.pb_cq.setSizePolicy(sizePolicy)
        self.pb_cq.setObjectName("pb_cq")
        self.verticalLayout_2.addWidget(self.pb_cq)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.setStretch(5, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1515, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Dicom"))
        self.dicomButton.setText(_translate("MainWindow", "Load DICOM File"))
        self.colormapBox.setItemText(0, _translate("MainWindow", "GRAY"))
        self.colormapBox.setItemText(1, _translate("MainWindow", "AUTUMN"))
        self.colormapBox.setItemText(2, _translate("MainWindow", "BONE"))
        self.colormapBox.setItemText(3, _translate("MainWindow", "COOL"))
        self.colormapBox.setItemText(4, _translate("MainWindow", "HOT"))
        self.colormapBox.setItemText(5, _translate("MainWindow", "HSV"))
        self.colormapBox.setItemText(6, _translate("MainWindow", "JET"))
        self.colormapBox.setItemText(7, _translate("MainWindow", "OCEAN"))
        self.colormapBox.setItemText(8, _translate("MainWindow", "PINK"))
        self.colormapBox.setItemText(9, _translate("MainWindow", "RAINBOW"))
        self.colormapBox.setItemText(10, _translate("MainWindow", "SPRING"))
        self.colormapBox.setItemText(11, _translate("MainWindow", "SUMMER"))
        self.colormapBox.setItemText(12, _translate("MainWindow", "WINTER"))
        self.label_5.setText(_translate("MainWindow", "Dicom Info"))
        self.privatecheckBox.setText(_translate("MainWindow", "Protected Display"))
        self.lbvideo.setText(_translate("MainWindow", "相机视图"))
        self.lbmodel.setText(_translate("MainWindow", "模型视图"))
        self.pb1.setText(_translate("MainWindow", "启动跟踪"))
        self.pb2.setText(_translate("MainWindow", "拟合"))
        self.pb3.setText(_translate("MainWindow", "待定"))
        self.pb4.setText(_translate("MainWindow", "退出"))
        self.pos_y.setText(_translate("MainWindow", "150"))
        self.pos_z.setText(_translate("MainWindow", "150"))
        self.nor_z.setText(_translate("MainWindow", "-1"))
        self.nor_y.setText(_translate("MainWindow", "0"))
        self.nor_x.setText(_translate("MainWindow", "0"))
        self.pb_readdata.setText(_translate("MainWindow", "确认"))
        self.lb32.setText(_translate("MainWindow", "0, 0, 0"))
        self.lb21.setText(_translate("MainWindow", "camera_pos"))
        self.lb22.setText(_translate("MainWindow", "0, 0, 0"))
        self.lb31.setText(_translate("MainWindow", "robot_pos"))
        self.lb12.setText(_translate("MainWindow", "--"))
        self.lb11.setText(_translate("MainWindow", "系统信息："))
        self.lb31_3.setText(_translate("MainWindow", "跟踪位置："))
        self.label_2.setText(_translate("MainWindow", "跟踪向量："))
        self.pos_x.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "跟踪距离："))
        self.tms2head.setText(_translate("MainWindow", "30"))
        self.label_4.setText(_translate("MainWindow", "mm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "camera"))
        self.pushButton.setText(_translate("MainWindow", "暂停"))
        self.pushButton_2.setText(_translate("MainWindow", "退出"))
        self.pushButton_3.setText(_translate("MainWindow", "示教"))
        self.pushButton_4.setText(_translate("MainWindow", "复位"))
        self.pushButton_5.setText(_translate("MainWindow", "运行"))
        self.lb32_2.setText(_translate("MainWindow", "TextLabel"))
        self.lb42_2.setText(_translate("MainWindow", "TextLabel"))
        self.lb21_2.setText(_translate("MainWindow", "TextLabel"))
        self.lb22_2.setText(_translate("MainWindow", "TextLabel"))
        self.lb31_2.setText(_translate("MainWindow", "TextLabel"))
        self.lb12_2.setText(_translate("MainWindow", "TextLabel"))
        self.lb41_2.setText(_translate("MainWindow", "TextLabel"))
        self.lb11_2.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Tab 1"))
        self.pb_txd.setText(_translate("MainWindow", "TX-"))
        self.pb_txa.setText(_translate("MainWindow", "TX+"))
        self.pb_tyd.setText(_translate("MainWindow", "TY-"))
        self.pb_tya.setText(_translate("MainWindow", "TY+"))
        self.pb_tzd.setText(_translate("MainWindow", "TZ-"))
        self.pb_tza.setText(_translate("MainWindow", "TZ+"))
        self.pb_tad.setText(_translate("MainWindow", "TA-"))
        self.pb_taa.setText(_translate("MainWindow", "TA+"))
        self.pb_tbd.setText(_translate("MainWindow", "TB-"))
        self.pb_tba.setText(_translate("MainWindow", "TB+"))
        self.pb_tcd.setText(_translate("MainWindow", "TC-"))
        self.pb_tca.setText(_translate("MainWindow", "TC+"))
        self.pb_j1d.setText(_translate("MainWindow", "J1-"))
        self.pb_j1a.setText(_translate("MainWindow", "J1+"))
        self.pb_j2d.setText(_translate("MainWindow", "J2-"))
        self.pb_j2a.setText(_translate("MainWindow", "J2+"))
        self.pb_j3d.setText(_translate("MainWindow", "J3-"))
        self.pb_j3a.setText(_translate("MainWindow", "J3+"))
        self.pb_j4d.setText(_translate("MainWindow", "J4-"))
        self.pb_j4a.setText(_translate("MainWindow", "J4+"))
        self.pb_j5d.setText(_translate("MainWindow", "J5-"))
        self.pb_j5a.setText(_translate("MainWindow", "J5+"))
        self.pb_j6d.setText(_translate("MainWindow", "J6-"))
        self.pb_j6a.setText(_translate("MainWindow", "J6+"))
        self.label.setText(_translate("MainWindow", "速度："))
        self.lineEdit.setText(_translate("MainWindow", "5"))
        self.pb_setspeed.setText(_translate("MainWindow", "更新"))
        self.pb_zt.setText(_translate("MainWindow", "暂停"))
        self.pb_tc.setText(_translate("MainWindow", "退出"))
        self.pb_sj.setText(_translate("MainWindow", "示教"))
        self.pb_fw.setText(_translate("MainWindow", "复位"))
        self.pb_yx.setText(_translate("MainWindow", "运行"))
        self.pb_cq.setText(_translate("MainWindow", "重启"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "robot"))
from qpaintlabel3 import QPaintLabel3
